### PR TITLE
2213 unable to identify duolingo coupon redemption

### LINKED ISSUE #2213: Unable to Identify Duolingo Coupon Redemption
Hello <@U055YR1QT0A>! First, a big thank you for the tech team on all the fantastic work in Duolingo and TC.

I wanted to bring up an issue regarding Batumike James. I shared a coupon with him in early May, and according to his TC profile, it was claimed on May 9th. However, as per the attached thread, he mentioned yesterday that although he added the coupon, it didn’t work on his end.

I tried to send him a new coupon but was unable to do so, as shown in the screenshot below. Sometimes coupons don’t work due to various reasons — for example, candidates may mistype the coupon code. To help troubleshoot, I would like to have access to the backend so I can verify coupon usage and check for any entry errors directly.

Before checking with the Duolingo team, it would be great to test sending a second coupon. If the second coupon also fails, perhaps there are country restrictions or other issues we need to flag with Duolingo.

Could you please advise on the following:

• Is it possible for me to get backend access to review how coupons are claimed and verify code entries?
• Now that the Duolingo English Test is integrated with TC, will I still be able to view new test results on the Duolingo admin account as before?
• Can the option to send another coupon be enabled on my end, so we can test this quickly?

Thanks again for your continuous support and hard work! :pray: fyi <@U02UM67Q2HF> <@UH4HJDYEP> <@ULFJLQM9A>

 <https://refugeejobsmarket.slack.com/files/U02E0NC9DJ4/F08T8Q2DWN6/img_1846.jpg>

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1747817222722019?thread_ts=1747817222.722019&cid=C42S4AJ73)

### PR DESCRIPTION
**Pull request by EhsanEhrari**

### CODE REVIEW

File: server/src/main/java/org/tctalent/server/api/admin/SystemAdminApi.java [hunk 1]
```diff
@@ -380,6 +385,29 @@ public DuolingoVerifyScoreResponse verifyScore(
...
 
+    /**
+     * Reassigns a new Duolingo coupon to a candidate and marks any previously assigned coupons as redeemed.
+     *
+     * @param candidateId The ID of the candidate to whom the new coupon will be assigned.
+     * @return A ResponseEntity containing the details of the newly assigned coupon.
+     * @throws NoSuchObjectException If the candidate or available coupons are not found.
+     */
+    @GetMapping("reassign-duolingo-coupon/{candidateId}")
+    public ResponseEntity<DuolingoCouponResponse> reassignDuolingoCoupon(@PathVariable("candidateId") Long candidateId) {
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/api/admin/SystemAdminApi.java]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Your code is using a vulnerable version of the Spring Framework that contains a remote code execution vulnerability exploitable through malicious HTTP requests. This poses a significant security risk as attackers can gain complete control of affected systems, potentially leading to data breaches, service disruption, or further network compromise. To remediate this issue, update to the latest patched version of Spring Framework (specific version depends on which CVE is affecting your installation) and consider implementing additional security layers such as web application firewalls that can detect and block malicious HTTP requests.

[Learn more](https://cwe.mitre.org/data/definitions/94.html)

File: server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java [hunk 2]
```diff
@@ -386,4 +386,51 @@ public int countAvailableProctoredCoupons() {
...
+    Optional<DuolingoCoupon> availableCoupon = couponRepository.findTop1ByCandidateIsNullAndCouponStatusAndTestType(
+        DuolingoCouponStatus.AVAILABLE, DuolingoTestType.PROCTORED);
+
+    if (availableCoupon.isEmpty()) {
+      throw new NoSuchObjectException(
+          "There are no available coupons to assign to the candidate. Please import more coupons from the settings page.");
+    }
+
+    // Assign the new coupon to the candidate
+    DuolingoCoupon newCoupon = availableCoupon.get();
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java:439]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are using `Optional` value which can hold either a value or not. The value held in the `Optional` can be accessed using the `get()` method, but it will throw a `NoSuchElementException` if there is no value present. To avoid the exception, calling the `isPresent()` or `ifPresent()` or `!isEmpty()` method should always be done before any call to `get()`. Alternatively, other methods such as `orElse(...)`, `orElseGet(...)` or `orElseThrow(...)` can be used to specify what to do with an empty `Optional`.

[CWE-476](https://cwe.mitre.org/data/definitions/476)

**Review by samschlicht — DISMISSED** [review]

File: server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java [hunk 3]
```diff
@@ -386,4 +386,51 @@ public int countAvailableProctoredCoupons() {
...
+  @Transactional
+  public DuolingoCouponResponse reassignProctoredCouponToCandidate(Long candidateId, User user)
+      throws NoSuchObjectException {
+    // Find the candidate
+    Candidate candidate = candidateRepository.findById(candidateId)
+        .orElseThrow(() -> new NoSuchObjectException("Candidate with ID " + candidateId + " not found"));
+
+    // Find all existing coupons for the candidate and mark them as REDEEMED
+    List<DuolingoCoupon> existingCoupons = couponRepository.findAllByCandidateId(candidateId);
+    for (DuolingoCoupon existingCoupon : existingCoupons) {
```
Comment (cazcam34) [inline server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java:403]: Hi @EhsanEhrari - when a coupon is marked as redeemed (due to it being uncertified) do we also need to resolve any duolingo tasks related to this coupon? 
Looking at the candidate that this issue was raised for (Candidate 264023) I can see he still has tasks outstanding even though the coupon is uncertified. Perhaps we also need to resolve any outstanding tasks for this coupon? Especially as it appears we assign another claim coupon task below.
I wonder if it's useful to make a note somewhere that this candidate has had the coupon reassigned. This could be done by marking the outstanding duolingo tasks with the status 'Abandoned' and add a comment saying that the coupon was uncertified and so manually reassigned. Just some thoughts!

Comment (EhsanEhrari) [reply server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java:403]: Hi @cazcam34 ,
Thank you for your insightful feedback and for raising this issue! I’ve updated the reassignProctoredToCandidate method in DuolingoCouponServiceImpl to resolve any active duolinogTest tasks for the candidate when a coupon is marked as redeemed due to being uncertified. Specifically, I find active tasks and update to mark them as inactive, set abandonedDate, and add a note in candidateNotes stating, “Coupon was uncertified and manually reassigned.” This should address the issue for candidates like 264023, ensuring their outstanding tasks are resolved before assigning a new claimCouponButton task.

I appreciate your suggestion to document the reassignment, and I think using candidateNotes with logging provides a clear audit trail. Please let me know if there are any other things I should include or if further refinements are needed!

Comment (cazcam34) [reply server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java:403]: Look great! :)

Comment (cazcam34) [reply server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java:403]: Look great! :)

**Review by cazcam34 — DISMISSED** [review]

File: server/src/main/java/org/tctalent/server/api/admin/SystemAdminApi.java [hunk 4]
```diff
@@ -380,6 +385,29 @@ public DuolingoVerifyScoreResponse verifyScore(
...
     }
 
+    /**
+     * Reassigns a new Duolingo coupon to a candidate and marks any previously assigned coupons as redeemed.
+     *
+     * @param candidateId The ID of the candidate to whom the new coupon will be assigned.
+     * @return A ResponseEntity containing the details of the newly assigned coupon.
+     * @throws NoSuchObjectException If the candidate or available coupons are not found.
+     */
+    @GetMapping("reassign-duolingo-coupon/{candidateId}")
```
Comment (camerojo) [inline server/src/main/java/org/tctalent/server/api/admin/SystemAdminApi.java]:
```suggestion
    @GetMapping("reassign-duolingo-coupon/{candidateNumber}")
```

Candidate number is better (which is a String, not a long). That is what is displayed everywhere on the TC browser app. Candidate id is only used internally. Candidate id is not the same as Candidate number. We have both for legacy reasons. One day there is a tech debt issue to get rid of Candidate ids and make Candidate number the primary key (and convert it to a long).

**Review by camerojo — CHANGES_REQUESTED** [review]
Natural confusion about a nasty bit of tech debt that we have in the TC - ie the difference between candidate id and candidate number. For anything coming from the Angular/Browser we need to use candidate number - because that is what users see.

File: server/src/main/java/org/tctalent/server/api/admin/SystemAdminApi.java (hunk 4 above)
Comment (EhsanEhrari) [reply server/src/main/java/org/tctalent/server/api/admin/SystemAdminApi.java]: Thanks for letting me know!

File: server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java [hunk 5]
```diff
@@ -386,4 +388,80 @@ public int countAvailableProctoredCoupons() {
...
+      couponRepository.save(existingCoupon);
+    }
+
+    // Find and resolve existing Duolingo-related task assignments
+    TaskImpl duolingoTestTask = taskService.getByName("duolingoTest");
+    List<TaskAssignmentImpl> taskAssignments = taskAssignmentService.findByTaskIdAndCandidateIdAndStatus(
+        duolingoTestTask.getId(), candidate.getId(), Status.active);
+    for (TaskAssignmentImpl taskAssignment : taskAssignments) {
+      taskAssignment.setStatus(Status.inactive);
+      taskAssignmentService.update(
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java:414]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Potential SQL Injection detected. Untrusted input is being directly included in an SQL query without proper parameterization. This can allow attackers to modify the query structure and execute arbitrary SQL commands. Use PreparedStatement with parameterized queries instead. Always validate and sanitize inputs before using them in queries. Learn more https://cwe.mitre.org/data/definitions/89.html

**Review by cazcam34 — DISMISSED** [review]

**Review by camerojo — DISMISSED** [review]

**Comment by EhsanEhrari** [comment]
Fixed the conflict in SystemAdminApi I need reapproval on this one please.

**Review by samschlicht — APPROVED** [review]

**Review by cazcam34 — APPROVED** [review]
