### PR TITLE
2416 implement postgres text search and ranked sort order on all combined job descriptions

### LINKED ISSUE #2416: Implement Postgres text search and ranked sort order on all combined job descriptions
This is built on #2385

Gathering all experience details together and treating as a whole. This is necessary when searching with AND logic - searching for text1 AND text2. It will fail if text1 is in one job description and text2 is in another. Job descriptions need to be concatenated together for text1 AND text2 to return true.

Needs to be a single field if it is going to be indexed. Field will be redundant computed field - computed from the concatenation of all descriptions. Probably the easiest way to do that is inside the Java entity - automatically recomputing the concatenation when any description changes, is added or deleted.

### PR DESCRIPTION
**Pull request by camerojo**
Built on #2385

### CODE REVIEW

File: server/src/main/java/org/tctalent/server/util/RegexHelpers.java [hunk 1]
```diff
@@ -40,6 +41,7 @@ public static List<String> extractLinkUrlsFromHtml(@Nullable String html) {
     }
 
     public static @NonNull String camelToSnakeCase(@NonNull String camel) {
-        return camel.replaceAll("([a-z])([A-Z]+)", "$1_$2").toLowerCase();
+        return camel.replaceAll("([a-z])([A-Z]+)", "$1_$2")
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/util/RegexHelpers.java]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

### Do not initialise a locale using hardcoded locale literals

Hardcoding a locale will make the code suitable only for that particular locale and will need refactor if the service needs to support multiple locales.

### Recommendation

Ideally, the refactor effort needed to support multiple locales should only be through config file changes and not code refractor. Use one of below suggestions as suited -
1. Use a separate configuration per locale to store all locale dependent attribute.
2. If you are processing a request, get the locale object from request context and use it.
3. Utilize Locale.Root for locale-independent code or default configurations.

For more information refer to the [wiki](https://w.amazon.com/bin/view/Alexa/Alexa_International/Alexa_I18N_Best_Practices/HardCoded-Locale/#HHardcodedLocale-LocaleLiteral).

File: server/src/main/java/org/tctalent/server/request/candidate/SearchCandidateRequest.java [hunk 2]
```diff
@@ -176,51 +177,93 @@ public SearchCandidateRequest() {
...
+            String nonIdSortFields = CandidateSearchUtils.buildNonIdFieldList(sort, getSimpleQueryString());
+            if (!nonIdSortFields.isEmpty()) {
+                sql += "," + nonIdSortFields;
+            }
+            sql += " from candidate";
+        }
+        return sql;
+    }
+
+    private String extractJoinAndWhereSQL(
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/request/candidate/SearchCandidateRequest.java]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this method is 51. By comparison, 99% of the methods in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the method has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this method or break it into multiple methods. For example, consider extracting the code blocks on lines 277-289, lines 300-308, lines 313-327, lines 419-459, lines 468-482 into separate methods.

File: server/src/main/java/org/tctalent/server/service/db/impl/CandidateSearchServiceImpl.java [hunk 3]
```diff
@@ -55,31 +55,19 @@ public class CandidateSearchServiceImpl implements CandidateSearchService {
...
         LogBuilder.builder(log).action("findCandidates")
-            .message("Query: " + sqlWithSort).logInfo();
+            .message("Query: " + sql).logInfo();
 
         //Create and execute the query to return the candidate ids
-        Query query = entityManager.createNativeQuery(sqlWithSort);
-        query.setFirstResult((int) pageable.getOffset());
-        query.setMaxResults(pageable.getPageSize());
-        List<Long> ids = executeIdsQuery(query);
+        Query query = entityManager.createNativeQuery(sql);
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/service/db/impl/CandidateSearchServiceImpl.java:119]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Potential SQL Injection detected. Untrusted input is being directly included in an SQL query without proper parameterization. This can allow attackers to modify the query structure and execute arbitrary SQL commands. Use PreparedStatement with parameterized queries instead. Always validate and sanitize inputs before using them in queries. Learn more https://cwe.mitre.org/data/definitions/89.html

**Review by sadatmalik — DISMISSED** [review]
