### PR TITLE
#453 Candidate portal missing status case

### LINKED ISSUE #453: Candidate portal login of candidates who have status unreachable incorrectly tells them that their registration is incomplete
The issue is in the home.component.html which uses an ngSwitch on candidate status.

There is no case for status=unreachable so the default case is used - which displays an inappropriate message.

### PR DESCRIPTION
**Pull request by camerojo**

### CODE REVIEW

File: ui/admin-portal/src/app/components/login/login.component.ts [hunk 1]
```diff
@@ -77,13 +77,14 @@ export class LoginComponent implements OnInit {
...
-        console.log(error);
-      }
-    );
+    // const action = 'login';
+    // this.reCaptchaV3Service.execute(action).subscribe(
+    //   (token) => this.loginWithToken(token),
+    //   (error) => {
+    //     console.log(error);
+    //   }
+    // );
```
Comment (sadatmalik) [inline ui/admin-portal/src/app/components/login/login.component.ts:86]: So this will bypass the recaptcha token - is this what we want to do?

File: ui/candidate-portal/src/app/components/account/login/login.component.ts [hunk 2]
```diff
@@ -71,13 +71,14 @@ export class LoginComponent implements OnInit {
...
-        console.log(error);
-      }
-    );
+    // const action = 'login';
+    // this.reCaptchaV3Service.execute(action).subscribe(
+    //   (token) => this.loginWithToken(token),
+    //   (error) => {
+    //     console.log(error);
+    //   }
+    // );
```
Comment (sadatmalik) [inline ui/candidate-portal/src/app/components/account/login/login.component.ts:80]: Same comment here as with the admin-portal login - bypassing recaptcha - is that intentional?

**Review by sadatmalik — COMMENTED** [review]
Just a question on the recaptcha token code

File: ui/admin-portal/src/app/components/login/login.component.ts (hunk 1 above)
Comment (camerojo) [reply ui/admin-portal/src/app/components/login/login.component.ts:86]: Yes - recaptcha is for the chop. It is no longer needed since we moved to MFA. Checking is alreday disabled on the server - has been for a long time.
My current "In progress" issue #311 will pull it out altogether.

**Review by sadatmalik — APPROVED** [review]
