### PR TITLE
fix: discarded directive, now uses disabled input on textarea

### LINKED ISSUE #2601: Bug: (UI rollover) 'disabled' input to tc-textarea not working
When `[disabled]="true"` is passed to the tc-textarea component, it isn't working.

Once fixed, uncomment this test, which should work: 
`candidate-shareable-notes-component.spec.ts#it('should disable textarea if not editable'`

### PR DESCRIPTION
**Pull request by samschlicht**

### CODE REVIEW

File: ui/admin-portal/src/app/components/util/candidate-shareable-notes/candidate-shareable-notes.component.ts [hunk 1]
```diff
@@ -61,16 +61,13 @@ export class CandidateShareableNotesComponent extends AutoSaveComponentBase
...
+      this.form.controls['shareableNotes'].patchValue(
+        this.candidate.shareableNotes,
+        { emitEvent: false }
+      );
     }
   }
 
-  isEditable(): boolean {
-    return this.authService.isEditableCandidate(this.candidate);
-  }
```
Comment (samschlicht) [inline ui/admin-portal/src/app/components/util/candidate-shareable-notes/candidate-shareable-notes.component.ts:75]: This is not required - the auth check takes place in the parent and is passed to the component as the `editable` input. Visibility is also handled by the parent. The component isn't used in any context where the parent doesn't handle the candidate.

**Review by hiba-machfej — APPROVED** [review]

**Review by camerojo — APPROVED** [review]
