### PR TITLE
Reaction + LinkPreview entity doc, small template change on sent posts, proper JPA implementation for Chat Post Link Previews

### LINKED ISSUE #1193: Doc for Reaction and LinkPreview entities and small logging change
John rightly pointed out that these entities could do with a bit of explanatory doc.

Also an opportunity to tidy up the overview doc for LinkPreviewService, which contains a typo. It also may be useful to add some doc to the implementation, since that's where the private scraping methods are.

UPDATE: While I'm at it, will just stop the service methods from logging the whole exception stack traces — it's unnecessary and makes the overall logs harder to read. Use e.getMessage() instead, which provides more than enough in this case.

### PR DESCRIPTION
**Pull request by samschlicht**
NB: combines fixes for #1193 and #1245 - they're both pretty small and mostly concern the same files. I think this is still manageable to review and avoids unnecessary conflict resolution. Let me know if not and I'll split them!

- Adds entity doc for Reaction and Link Preview
- Properly implements bidirectional one-to-many relationship for Chat Post > Link Preview, including null check which is the bug that @camerojo pointed out
- Small template change on sent posts to place reactions below link previews:

Screenshot 2024-08-12 at 3 12 16 PM

### CODE REVIEW

File: server/src/main/java/org/tctalent/server/model/db/LinkPreview.java [hunk 1]
```diff
@@ -17,44 +17,133 @@
...
 @Setter
 @Entity
 @Table(name = "link_preview")
 @SequenceGenerator(name = "seq_gen", sequenceName = "link_preview_id_seq", allocationSize = 1)
 public class LinkPreview extends AbstractDomainObject<Long> {
 
+    @Id
+    @GeneratedValue
+    private Long id;
+
```
Comment (camerojo) [inline server/src/main/java/org/tctalent/server/model/db/LinkPreview.java]: No need to add this - it is inherited from AbstractDomainObject<Long>.

Why did you feel you needed to add it?

File: server/src/main/java/org/tctalent/server/model/db/LinkPreview.java [hunk 2]
```diff
@@ -17,44 +17,133 @@
...
+     */
     @Nullable
     private String faviconUrl;
-}
+
+    /**
+     * We override hashCode and equals here to make sure that two entities with the same important
+     * data (like the same ID) are treated as the same, even if they are different objects in memory.
+     * This is particularly important with one-to-many relationships because the child entities
+     * might be used in a set or map, which check for equality; or removal from the parent entity's
```
Comment (camerojo) [inline server/src/main/java/org/tctalent/server/model/db/LinkPreview.java]: No need to add all this - it is inherited from AbstractDomainObject

**Review by camerojo — CHANGES_REQUESTED** [review]
See comments - inheriting from AbstractDomainObject gives you a lot of what you need - so you don't have to do it.

**Review by camerojo — APPROVED** [review]
Approved!
