### PR TITLE
fix: SF opp stage set correctly when job published w skip candidate search selected

### LINKED ISSUE #2264: Publish Job sets SF counterpart to wrong stage
Again, discovered while writing tests for JobServiceImpl.

In this block (L614-636) we set the stage of a TC Job to candidateSearch if `skipCandidateSearch = false` and `visaEligibility` if `skipCandidateSearch = true`. But then we ignore that logic when updating the Next Step and SF Job:

```
if (stage.compareTo(JobOpportunityStage.candidateSearch) < 0 )  {
            //Current stage is before CandidateSearch so update it

            //New stage will depend on skipCandidateSearch
            JobOpportunityStage nextStage =
                job.isSkipCandidateSearch() ? JobOpportunityStage.visaEligibility :
                    JobOpportunityStage.candidateSearch;
            job.setStage(nextStage);

            //Update Salesforce stage to match - setting Next Step and Due date
            final LocalDate submissionDueDate = job.getSubmissionDueDate();

            //Next step
            final String processedNextStep =
                nextStepProcessingService.processNextStep(
                    job, "Waiting to receive candidate CVs for review"
                );
            job.setNextStep(processedNextStep);

            salesforceService.updateEmployerOpportunityStage(
                job, JobOpportunityStage.candidateSearch, processedNextStep, submissionDueDate
            );
        }
```

### PR DESCRIPTION
**Pull request by samschlicht**

### CODE REVIEW

File: server/src/main/java/org/tctalent/server/service/db/impl/JobServiceImpl.java [hunk 1]
```diff
@@ -628,7 +628,7 @@ public void loadJobOppsAndCandidateOpps() {
             job.setNextStep(processedNextStep);
 
             salesforceService.updateEmployerOpportunityStage(
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/service/db/impl/JobServiceImpl.java:630]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Potential SQL Injection detected. Untrusted input is being directly included in an SQL query without proper parameterization. This can allow attackers to modify the query structure and execute arbitrary SQL commands. Use PreparedStatement with parameterized queries instead. Always validate and sanitize inputs before using them in queries. Learn more https://cwe.mitre.org/data/definitions/89.html

**Review by hiba-machfej — APPROVED** [review]

**Review by camerojo — APPROVED** [review]
