### PR TITLE
1903 csv import fails due to changing column order in exported csv

### LINKED ISSUE #1903: CSV Import Fails Due to Changing Column Order in Exported CSV
Initially, the CSV import functionality was implemented with the assumption that the column order in the exported CSV files would remain consistent. However, during testing today, it was observed that the column order changes when exporting CSV files from the Duolingo dashboard. This causes the import process to fail since it relies on fixed column indices.

### PR DESCRIPTION
**Pull request by EhsanEhrari**

### CODE REVIEW

File: server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java [hunk 1]
```diff
@@ -74,44 +74,77 @@ public DuolingoCouponServiceImpl(DuolingoCouponRepository couponRepository,
...
-    try (CSVReader reader = new CSVReader(
-        new InputStreamReader(file.getInputStream(), StandardCharsets.UTF_8))) {
-      reader.readNext(); // Skip header row
-      String[] line;
+    try (CSVReader reader = new CSVReader(new InputStreamReader(file.getInputStream(), StandardCharsets.UTF_8))) {
+      // Read the header row of the CSV and map column names to their indices
+      String[] headers = reader.readNext();
+      if (headers == null) {
+        // Throw an exception if the CSV file does not have a header row
+        throw new ImportFailedException("CSV header is missing");
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Exception [ImportFailedException] is explicitly thrown on this line but is caught in the outer catch clause with generic exception on line [143].  Consider adding a catch clause of this specific exception in the outer try statement.

File: server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java [hunk 2]
```diff
@@ -74,44 +74,77 @@
...
 
-        String couponCode = line[0];
-        if (seenCouponCodes.contains(couponCode)) {
-          continue; // Skip if already processed
+      // Validate that all required columns are present
+      String[] requiredColumns = {"coupon code", "expiration date", "date sent", "coupon status"};
+      for (String column : requiredColumns) {
+        if (!columnIndex.containsKey(column)) {
+          // Throw exception if any required column is missing
+          throw new ImportFailedException("Missing required column: " + column);
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Exception [ImportFailedException] is explicitly thrown on this line but is caught in the outer catch clause with generic exception on line [143].  Consider adding a catch clause of this specific exception in the outer try statement.

File: server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java [hunk 3]
```diff
@@ -74,44 +74,77 @@
 
   @Override
   @Transactional
-  public void importCoupons(MultipartFile file) {
+  public void importCoupons(MultipartFile file) throws ImportFailedException {
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java:79]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this method is 11. By comparison, 98% of the methods in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the method has a high number of decisions and it can make the logic difficult to understand and test. We recommend that you simplify this method or break it into multiple methods.

File: server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java [hunk 4]
```diff
@@ -74,44 +74,77 @@
...
       }
+
+      // Save all new coupons to the database if there are any
       if (!newCoupons.isEmpty()) {
         couponRepository.saveAll(newCoupons);
       }
-    } catch (IOException | CsvValidationException e) {
-      throw new ImportFailedException(e);
+
+    } catch (Exception e) {
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/service/db/impl/DuolingoCouponServiceImpl.java]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**: While re-throwing the caught exception with modifications , information about the caught exception is being lost, including information about the stack trace of the exception.

**Fix**: If the caught exception object does not contain sensitive information, consider passing it as the &#34;rootCause&#34; or inner exception parameter to the constructor of the new exception before throwing the new exception. (Note that not all exception constructors support inner exceptions. Use a wrapper exception that supports inner exceptions.) 
[Learn more](https://www.ibm.com/support/pages/best-practice-catching-and-re-throwing-java-exceptions)

Suggested remediation:
Consider passing the exception object either as  &#34;rootCause&#34; or as an inner exception parameter, to the constructor of the new exception before throwing new exception. This will help keep stack trace.
```
@@ -143,3 +143,3 @@
     } catch (Exception e) {
-      throw new ImportFailedException(&#34;An error occurred during the import process: &#34; + e.getMessage());
+      throw new ImportFailedException(&#34;An error occurred during the import process: &#34; + e.getMessage(), e);
     }

```

**Review by camerojo — APPROVED** [review]
