### PR TITLE
2059 readonly review fix up the following entry points failures auto logout

### LINKED ISSUE #2059: ReadOnly review: Fix up the following entry points failures (auto logout)
- [x] Job - Put Job summary (automatically puts upon ngChanges - causing immediate logout when flicking between table) (http://localhost:8080/api/admin/job/70/summary)

- [x] Job Tab - TBB Candidate Chats tab logout

- [x] Job Tab - Filter checkboxes aren't clickable (jobs and cases)

- [x] Can't change columns on my list

- [x] clicking Intelligence logs out

- [x] Select a shareable doc from dropdown (shouldn't be done on front end for read only)

- [x] Can see input old intake and complete intake buttons - if clicked they logout. Should hide buttons from read only.

- [x] Adding a suggested search to a job

- [x] Download CV logs out 

- [x] If data entered into intake fields logs out - should disable ability to enter data into intake fields on front end (new issue to create directive to do this easily in bulk see issue #2162)

### PR DESCRIPTION
**Pull request by cazcam34**
And in some cases remove ability to access the end point on the front end

### CODE REVIEW

File: ui/admin-portal/src/app/components/chat/view-chat-posts/view-chat-posts.component.ts [hunk 1]
```diff
@@ -99,7 +99,7 @@ export class ViewChatPostsComponent extends PostsComponentBase
             (post) => post.reactionPickerVisible)
 
     // Check if any picker is open
-    if(this.editor.emojiPickerVisible || postWithOpenPicker != null) {
+    if(this.editor?.emojiPickerVisible || postWithOpenPicker != null) {
```
Comment (samschlicht) [inline ui/admin-portal/src/app/components/chat/view-chat-posts/view-chat-posts.component.ts:102]: Nice catch!

**Review by samschlicht — DISMISSED** [review]

**Review by sadatmalik — DISMISSED** [review]

**Review by samschlicht — APPROVED** [review]

**Review by sadatmalik — APPROVED** [review]
