### PR TITLE
1160 stats fail on searches which returns large numbers of candidates 32000

### LINKED ISSUE #1160: Stats fail on searches which returns large numbers of candidates (> 32000)
Follows on from issue #1054

### PR DESCRIPTION
**Pull request by camerojo**
Note that this code should be safe because it preserves all the existing code that run stats. It just introduces another way of running the same stats (in the new CandidateStatsService). The other substantive change is the extractSQL method of SearchCandidateRequest. This extracts the query SQL corresponding to the request. This is alternative to generating a CriteriaAPI query by passing the request to CandidateSpecification.

The new way of running stats is presented independently as a "New Run stats" button, next to the standard "Run stats" button.

We can verify in production that the two ways of running stats produce the same results. Once we are confident of that we can remove the old way - and get rid of all of its code.

Note that all the @Test annotations have been commented out in @SpringBootTest's because they won't work in a GitHub build environment.

### Warning

This code also adds privileged: true to the docker-compose.yml - see https://refugeejobsmarket.slack.com/archives/C0583HJ9CHM/p1721692620716589

### CODE REVIEW

File: server/src/main/java/org/tctalent/server/request/candidate/SearchCandidateRequest.java [hunk 1]
```diff
@@ -152,6 +166,226 @@ public SearchCandidateRequest() {
         super(Sort.Direction.DESC, new String[]{"id"});
     }
 
+    /**
+     * Extracts the database query SQL corresponding to the given search request.
+     *
+     * @param nativeQuery True if native database SQL is required, otherwise JPQL is returned
+     * @return String containing the SQL or JPQL
+     */
+    public String extractSQL(boolean nativeQuery,
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/request/candidate/SearchCandidateRequest.java:175]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this method is 47. By comparison, 99% of the methods in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the method has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this method or break it into multiple methods. For example, consider extracting the code blocks on lines 190-202, lines 213-221, lines 226-240, lines 326-366, lines 368-379 into separate methods.

File: server/src/main/java/org/tctalent/server/request/candidate/SearchCandidateRequest.java [hunk 2]
```diff
@@ -152,6 +166,226 @@
...
+        // SURVEY TYPE SEARCH
+        if (!ObjectUtils.isEmpty(getSurveyTypeIds())) {
+            String values = getSurveyTypeIds().stream()
+                .map(Objects::toString).collect(Collectors.joining(","));
+            ands.add("candidate.survey_type_id in (" + values + ")");
+        }
+
+        // REFERRER
+        final String referrerParam =
+            getRegoReferrerParam() == null ? null : getRegoReferrerParam().trim().toLowerCase();
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/request/candidate/SearchCandidateRequest.java:259]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

#### toLowerCase [](|2045d6a2-68fa-4cde-87a6-566ffddb2b76|)

The parameterless versions of `String.toLowerCase()` and `String.toUpperCase()` use the default locale of the JVM when transforming strings. This can have unintended results, including difficult-to-debug transient failures because case mapping differs based on locale. 

**Even if you aren’t writing code for a user experience that’s displayed to a customer**, system internal code often uses case folding to normalize strings for comparison.
Not doing so can missing locale lead to errors when running on systems that are configured to use a different system locale. This can include developer desktops or build servers (not just your fleet hosts): many hours have been spent debugging errors that only occur on a specific machine due to its locale configuration.

#### Recommended solutions:

Always pass in a `Locale`.

**Language or locale-dependent processing:**

Get the locale from the platform, use the language of the content, or configure it in your code and pass that to the method.
```
String firstName = &#34;Ichabod&#34;; 
Locale locale = // Where you obtain the locale from is platform dependent
String lowerCaseFirstName = firstName.toLowerCase(locale);
``` 

**Internal processing that isn’t locale-dependent:**

*Example: S3 bucket name*

Always specify the language/country-neutral locale `Locale.ROOT`. 

```
String imgTag = &#34;IMG&#34;; 
if (&#34;img&#34;.equals(imgTag.toLowerCase(Locale.ROOT)) {    
// do something 
}
```

File: server/src/main/java/org/tctalent/server/util/locale/LocaleHelper.java [hunk 3]
```diff
@@ -112,6 +119,22 @@ public class LocaleHelper {
...
+     * @param localTime Local time
+     * @param timezone Timezone string - if null or blank UTC timezone is used
+     * @return An OffsetDateTime
+     */
+    public static OffsetDateTime getOffsetDateTime(
+        LocalDate localDate, LocalTime localTime, @Nullable String timezone) {
+        ZoneOffset offset = ZoneOffset.UTC;
+        if (!ObjectUtils.isEmpty(timezone)) {
+            offset = ZoneId.of(timezone).getRules().getOffset(Instant.now());
+        }
```
Comment (sadatmalik) [inline server/src/main/java/org/tctalent/server/util/locale/LocaleHelper.java:139]: Handle a possible Runtime exception here. If so, does it make sense to fall back to UTC and continue processing:
```
    if (!ObjectUtils.isEmpty(timezone)) {
        try {
            offset = ZoneId.of(timezone).getRules().getOffset(Instant.now());
        } catch (DateTimeException e) {
            System.err.println("Invalid timezone provided: " + timezone + ". Falling back to UTC.");
        }
    }
```

**Review by sadatmalik — DISMISSED** [review]
Love this!

File: server/src/main/java/org/tctalent/server/util/locale/LocaleHelper.java (hunk 3 above)
Comment (camerojo) [reply server/src/main/java/org/tctalent/server/util/locale/LocaleHelper.java:139]: Nice one - added it in (with unit test!)
